#!/bin/bash

# remove all existing pipes
rm -rf pipes && mkdir pipes

# start server 

if [ $# -eq 1 ] && [ "$1" = "--debug" ]; then
    echo "starting server with warnings enabled"
    cd server && python3 main.py && cd -
else    
    echo "starting server with warnings disabled"
    cd server && python3 main.py 2>/dev/null && cd -
fi
