#!/bin/bash

# remove all existing pipes
rm -rf pipes && mkdir pipes

# start server 
DEBUG=false

while [ $# -gt 0 ]; do
    if [ "$1" = "--debug" ]; then
        DEBUG=true
    else
        echo "Unknown option: $1"
        exit 1
    fi
    shift
done

if [ "$DEBUG" = true ]; then
    cd server && python3 main.py && cd -
else
    cd server && python3 main.py 2>/dev/null && cd -
fi
